Repository woowahan-hee-three/woowa-reservation, pull requests merged in 2019-12, with the labels that each got.

#6 Calendar: 특정 날짜 이벤트 조회
  .gitignore
  build.gradle
  src/main/java/com/h3/reservation/ReservationApplication.java
  src/main/java/com/h3/reservation/calendar/CalendarService.java
  src/main/java/com/h3/reservation/calendar/WebConfig.java
  src/main/java/com/h3/reservation/calendar/domain/CalendarId.java
  src/main/java/com/h3/reservation/calendar/domain/ReservationDateTime.java
  src/main/java/com/h3/reservation/calendar/exception/FetchingEventsFailedException.java
  src/main/resources/application.properties
  src/test/java/com/h3/http/calendar.http
  src/test/java/com/h3/reservation/calendar/CalendarServiceTest.java
  src/test/java/com/h3/reservation/calendar/domain/ReservationDateTimeTest.java
Labels: enhancement

#12 Calendar: 특정 시각 이벤트 조회
  src/main/java/com/h3/reservation/calendar/domain/ReservationDateTime.java
  src/main/java/com/h3/reservation/calendar/domain/exception/InvalidDateTimeRangeException.java
  src/test/java/com/h3/reservation/calendar/CalendarServiceTest.java
  src/test/java/com/h3/reservation/calendar/domain/ReservationDateTimeTest.java
Labels: enhancement

#20 Calendar : 시간 범위로 조회하는 로직
  src/main/java/com/h3/reservation/calendar/CalendarService.java
  src/main/java/com/h3/reservation/calendar/domain/ReservationDateTime.java
  src/test/java/com/h3/http/calendar.http
  src/test/java/com/h3/reservation/calendar/CalendarServiceTest.java
  src/test/java/com/h3/reservation/calendar/domain/ReservationDateTimeTest.java
Labels: enhancement

#42 Calendar: 회의실 예약 기능
  src/main/java/com/h3/reservation/calendar/CalendarService.java
  src/main/java/com/h3/reservation/calendar/NotAvailableReserveEventException.java
  src/main/java/com/h3/reservation/calendar/WebConfig.java
  src/main/java/com/h3/reservation/calendar/domain/CalendarEvents.java
  src/main/java/com/h3/reservation/calendar/domain/ReservationDateTime.java
  src/main/java/com/h3/reservation/calendar/domain/ReservationDetails.java
  src/main/java/com/h3/reservation/calendar/utils/SummaryParser.java
  src/main/java/com/h3/reservation/common/MeetingRoom.java
  src/main/java/com/h3/reservation/slackcalendar/converter/ReservationConverter.java
  src/main/java/com/h3/reservation/slackcalendar/service/SlackCalendarService.java
  src/main/resources/application.properties
  src/test/java/com/h3/reservation/calendar/CalendarServiceTest.java
  src/test/java/com/h3/reservation/calendar/domain/CalendarEventsTest.java
  src/test/java/com/h3/reservation/calendar/utils/SummaryParserTest.java
  src/test/java/com/h3/reservation/slackcalendar/converter/calendar/ReservationConverterTest.java
  src/test/java/com/h3/reservation/slackcalendar/service/SlackCalendarServiceTest.java
Labels: enhancement

#75 Calendar: 삭제 기능 구현
  src/main/java/com/h3/reservation/calendar/CalendarService.java
  src/main/java/com/h3/reservation/calendar/EventNotFoundException.java
  src/main/java/com/h3/reservation/slackcalendar/service/SlackCalendarService.java
  src/test/java/com/h3/reservation/calendar/CalendarServiceTest.java
Labels: enhancement

#66 docs: 조회 기능 사용법 작성
  README.md
Labels: documentation

#79 [#78] refactor: delete API를 id 기반으로 수정
  src/main/java/com/h3/reservation/calendar/CalendarService.java
  src/main/java/com/h3/reservation/calendar/exception/DeletingEventFailedException.java
  src/test/java/com/h3/reservation/calendar/CalendarServiceTest.java
Labels: refactor

#82 id로 Event 조회하는 기능
  src/main/java/com/h3/reservation/calendar/CalendarService.java
  src/main/java/com/h3/reservation/calendar/EventNotFoundException.java
  src/main/java/com/h3/reservation/calendar/domain/CalendarEvents.java
  src/main/java/com/h3/reservation/calendar/domain/ReservationDateTime.java
  src/main/java/com/h3/reservation/calendar/exception/InsertingEventFailedException.java
  src/main/java/com/h3/reservation/calendar/utils/SummaryParser.java
  src/main/java/com/h3/reservation/common/ReservationDetails.java
  src/test/java/com/h3/reservation/calendar/CalendarServiceTest.java
Labels: enhancement

#87 [#83] feat: Event 수정 기능 추가
  src/main/java/com/h3/reservation/calendar/CalendarService.java
  src/main/java/com/h3/reservation/calendar/domain/ReservationDateTime.java
  src/main/java/com/h3/reservation/calendar/exception/UpdatingEventFailedException.java
  src/test/java/com/h3/reservation/calendar/CalendarServiceTest.java
Labels: enhancement

#92 [#91] fix: Event 수정 시 자기 자신을 제외하고 이벤트 존재성 체크
  src/main/java/com/h3/reservation/calendar/CalendarService.java
  src/main/java/com/h3/reservation/calendar/domain/CalendarEvents.java
  src/test/java/com/h3/reservation/calendar/domain/CalendarEventsTest.java
Labels: bug

#97 [#96] fix: 특정 시간으로 조회하는 로직 수정
  src/main/java/com/h3/reservation/calendar/CalendarService.java
  src/main/java/com/h3/reservation/calendar/domain/ReservationDateTime.java
  src/test/java/com/h3/reservation/calendar/CalendarServiceTest.java
  src/test/java/com/h3/reservation/calendar/domain/ReservationDateTimeTest.java
Labels: bug

#102 Refactor summary parser: 중복 제거
  src/main/java/com/h3/reservation/calendar/domain/CalendarEvents.java
  src/main/java/com/h3/reservation/calendar/utils/SummaryParser.java
  src/main/java/com/h3/reservation/common/MeetingRoom.java
  src/main/java/com/h3/reservation/slackcalendar/converter/ReservationConverter.java
  src/main/java/com/h3/reservation/slackcalendar/converter/ReservationDetailsConverter.java
  src/main/java/com/h3/reservation/slackcalendar/domain/Reservation.java
  src/main/java/com/h3/reservation/slackcalendar/service/SlackCalendarService.java
  src/main/java/com/h3/reservation/utils/BasicParser.java
  src/main/java/com/h3/reservation/utils/InvalidSummaryException.java
  src/test/java/com/h3/reservation/calendar/utils/SummaryParserTest.java
  src/test/java/com/h3/reservation/slackcalendar/converter/ReservationConverterTest.java
  src/test/java/com/h3/reservation/slackcalendar/converter/ReservationDetailsConverterTest.java
  src/test/java/com/h3/reservation/slackcalendar/converter/calendar/ReservationConverterTest.java
  src/test/java/com/h3/reservation/slackcalendar/service/SlackCalendarServiceTest.java
  src/test/java/com/h3/reservation/utils/BasicParserTest.java
Labels: refactor

#103 description이 없는 Event들도 조회 가능하도록 변경
  src/main/java/com/h3/reservation/slackcalendar/converter/ReservationDetailsConverter.java
  src/test/java/com/h3/reservation/slackcalendar/converter/ReservationDetailsConverterTest.java
Labels: refactor

#107 Docs readme update
  README.md
Labels: documentation
